### ISSUE TITLE
brew install pdftk fails on make bootstrap step

### ISSUE THREAD

**Issue by brilang** [docmunch/homebrew-pdftk#5]
I performed the steps to install pdftk:
brew tap docmunch/pdftk
brew install pdftk

Transcript of terminal session:
==> Installing pdftk from docmunch/homebrew-pdftk
==> Installing dependencies for pdftk: ecj, gmp, mpfr, libmpc, isl, cloog, gcc
==> Installing pdftk dependency: ecj
==> Downloading ftp://sourceware.org/pub/java/ecj-4.5.jar
######################################################################## 100.0%
🍺  /usr/local/Cellar/ecj/4.5: 2 files, 1.4M, built in 4 seconds
==> Installing pdftk dependency: gmp
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.0.0a.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gmp-6.0.0a.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.0.0a: 15 files, 3.2M
==> Installing pdftk dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-3.1.2-p11.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mpfr-3.1.2-p11.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/3.1.2-p11: 24 files, 3.5M
==> Installing pdftk dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.0.3.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libmpc-1.0.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.0.3: 10 files, 380K
==> Installing pdftk dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.12.2.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring isl-0.12.2.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/isl/0.12.2: 55 files, 3.1M
==> Installing pdftk dependency: cloog
==> Downloading https://homebrew.bintray.com/bottles/cloog-0.18.1.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring cloog-0.18.1.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/cloog/0.18.1: 33 files, 560K
==> Installing pdftk dependency: gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
######################################################################## 100.0%
==> ../configure --build=x86_64-apple-darwin14.1.0 --prefix=/usr/local/Cellar/gcc/4.9.2_1 --libdir=/usr/local/Cellar/gcc/4.9.2_1/lib
==> make bootstrap

The last step never completed. I eventually hit Ctrl-C to stop the process and tried again:
brew install pdftk
==> Installing pdftk from docmunch/homebrew-pdftk
==> Installing pdftk dependency: gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-4.9.2.tar.bz2
	^[[Z==> ../configure --build=x86_64-apple-darwin14.1.0 --prefix=/usr/local/Cellar/gcc/4.9.2_1 --libdir=/usr/local/Cellar/gcc/4.9.2_1/lib
==> make bootstrap

It's still stopped at that step. The top of the terminal window keeps switching between different commands at very high speed, so I think it's still doing something, but I'm not sure. 

Please help me figure out what's going on so I can get pdftk installed.

**Comment by brilang** [comment]
Never mind. It eventually (like 20+ minutes) finished and is now installed.

**Comment by spl** [comment]
@brilang Thanks for the report. Sorry that you had to wait so long.

The delay you encountered is due to building the `gcc` compiler. It is unfortunate that `pdftk` depends on the `gcc` formula instead of the Xcode compiler, `clang`. Not only that, but `pdftk` requires the Java support of `gcc` (i.e. `gcj`), which is not by default enabled in the Homebrew formula of `gcc`. This means that `pdftk` will probably always require a source build of `gcc` instead of using a pre-packaged bottle. And, since `gcc` is such a large piece of software, the build takes a long time.

I hope `pdftk` otherwise works out for you.

**Comment by brilang** [comment]
pdftk worked fine.
Perhaps adding a note to the documentation that mentions the long compile
time would help.

Thanks.

--
*Brian Lang*
It Starts With Scouts | Bring on the Adventure | Be Prepared

**Comment by stevenspiel** [comment]
Thanks for the tip, waiting on mine now...
